WITH
LastSubmitOrForward AS (
    SELECT
        AH.OBJECT_ID,
        AH.PERFORMER_ID,
        AH.ACTION_DATE,
        AH.ACTION_CODE,
        ROW_NUMBER() OVER (PARTITION BY AH.OBJECT_ID ORDER BY AH.SEQUENCE_NUM DESC) AS RN
    FROM PO_ACTION_HISTORY AH
    WHERE AH.OBJECT_TYPE_CODE IN ('PO', 'PA')
      AND AH.ACTION_CODE      IN ('SUBMIT', 'FORWARD')
),
LastApprovalAction AS (
    SELECT
        AH.OBJECT_ID,
        AH.PERFORMER_ID AS LAST_ACTOR_PERSON_ID,
        AH.ACTION_CODE  AS LAST_ACTION_CODE,
        ROW_NUMBER() OVER (PARTITION BY AH.OBJECT_ID ORDER BY AH.SEQUENCE_NUM DESC) AS RN
    FROM PO_ACTION_HISTORY AH
    WHERE AH.OBJECT_TYPE_CODE IN ('PO', 'PA')
      AND AH.ACTION_CODE      IN ('APPROVE', 'REJECT', 'FORWARD', 'SUBMIT')
),
FirstRequester AS (
    SELECT
        PDA.PO_HEADER_ID,
        MIN(PDA.DELIVER_TO_PERSON_ID) KEEP (DENSE_RANK FIRST ORDER BY PDA.DISTRIBUTION_NUM) AS REQUESTER_PERSON_ID,
        MIN(PDA.CODE_COMBINATION_ID)  KEEP (DENSE_RANK FIRST ORDER BY PDA.DISTRIBUTION_NUM) AS CCID
    FROM PO_DISTRIBUTIONS_ALL PDA
    WHERE PDA.DELIVER_TO_PERSON_ID IS NOT NULL
    GROUP BY PDA.PO_HEADER_ID
),
PersonManager AS (
    SELECT
        PAS.PERSON_ID,
        PAS.MANAGER_ID AS MANAGER_PERSON_ID
    FROM PER_ASSIGNMENT_SUPERVISORS_F PAS
    WHERE PAS.MANAGER_TYPE = 'LINE_MANAGER'
      AND TRUNC(SYSDATE) BETWEEN PAS.EFFECTIVE_START_DATE AND PAS.EFFECTIVE_END_DATE
),
POLineTotals AS (
    SELECT
        PLA.PO_HEADER_ID,
        SUM(NVL(PLA.AMOUNT, NVL(PLA.QUANTITY, 0) * NVL(PLA.UNIT_PRICE, 0))) AS TOTAL_AMOUNT
    FROM PO_LINES_ALL PLA
    WHERE NVL(PLA.CANCEL_FLAG, 'N') = 'N'
    GROUP BY PLA.PO_HEADER_ID
)
SELECT
    PHA.SEGMENT1                                AS PO_NUMBER,
    PHA.TYPE_LOOKUP_CODE                        AS PO_TYPE,
    PHA.DOCUMENT_STATUS                         AS STATUS,
    LSF.ACTION_CODE                             AS LAST_WORKFLOW_ACTION,
    TRUNC(LSF.ACTION_DATE)                      AS PENDING_SINCE,
    TRUNC(SYSDATE) - TRUNC(LSF.ACTION_DATE)     AS DAYS_PENDING,
    CASE
        WHEN LAA.LAST_ACTION_CODE IN ('APPROVE', 'REJECT')
            THEN 'LAST ACTOR already approved or rejected this level'
        WHEN LAA.LAST_ACTION_CODE = 'FORWARD'
            THEN 'FORWARDED TO - see SUBMITTER column'
        ELSE 'PENDING - next approver not yet in history'
    END                                         AS APPROVER_STATUS_NOTE,
    NVL(
        CASE WHEN LAA.LAST_ACTION_CODE = 'FORWARD' THEN LastActorN.DISPLAY_NAME END,
        SubMgrN.DISPLAY_NAME
    )                                           AS MOST_LIKELY_NEXT_APPROVER,
    SubmitterN.DISPLAY_NAME                     AS SUBMITTER,
    SubMgrN.DISPLAY_NAME                        AS CAND1_SUBMITTER_MANAGER,
    SubMgr2N.DISPLAY_NAME                       AS CAND2_SUBMITTER_SKIP_LEVEL,
    ReqN.DISPLAY_NAME                           AS REQUESTER,
    ReqMgrN.DISPLAY_NAME                        AS CAND3_REQUESTER_MANAGER,
    BuyerN.DISPLAY_NAME                         AS BUYER,
    BuyerMgrN.DISPLAY_NAME                      AS CAND4_BUYER_MANAGER,
    GCC.SEGMENT1 || '.' || GCC.SEGMENT2 || '.' || GCC.SEGMENT3 || '.' ||
    GCC.SEGMENT4 || '.' || NVL(GCC.SEGMENT5, '')                  AS GL_ACCOUNT,
    GCC.SEGMENT2                                AS COST_CENTER,
    PLT.TOTAL_AMOUNT                            AS PO_TOTAL_AMOUNT,
    PHA.CURRENCY_CODE                           AS CURRENCY,
    PHA.PRC_BU_ID                               AS PROC_BU_ID,
    HP.PARTY_NAME                               AS SUPPLIER_NAME,
    PS.SEGMENT1                                 AS SUPPLIER_NUMBER
FROM PO_HEADERS_ALL PHA
LEFT JOIN POZ_SUPPLIERS PS ON PS.VENDOR_ID = PHA.VENDOR_ID
LEFT JOIN HZ_PARTIES    HP ON HP.PARTY_ID   = PS.PARTY_ID
LEFT JOIN LastSubmitOrForward LSF ON LSF.OBJECT_ID = PHA.PO_HEADER_ID AND LSF.RN = 1
LEFT JOIN LastApprovalAction  LAA ON LAA.OBJECT_ID = PHA.PO_HEADER_ID AND LAA.RN = 1
LEFT JOIN PER_PERSON_NAMES_F_V LastActorN
    ON  LastActorN.PERSON_ID = LAA.LAST_ACTOR_PERSON_ID
    AND LastActorN.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN LastActorN.EFFECTIVE_START_DATE AND LastActorN.EFFECTIVE_END_DATE
LEFT JOIN PER_PERSON_NAMES_F_V SubmitterN
    ON  SubmitterN.PERSON_ID = LSF.PERFORMER_ID
    AND SubmitterN.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN SubmitterN.EFFECTIVE_START_DATE AND SubmitterN.EFFECTIVE_END_DATE
LEFT JOIN PersonManager SubMgr ON SubMgr.PERSON_ID = LSF.PERFORMER_ID
LEFT JOIN PER_PERSON_NAMES_F_V SubMgrN
    ON  SubMgrN.PERSON_ID = SubMgr.MANAGER_PERSON_ID
    AND SubMgrN.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN SubMgrN.EFFECTIVE_START_DATE AND SubMgrN.EFFECTIVE_END_DATE
LEFT JOIN PersonManager SubMgr2 ON SubMgr2.PERSON_ID = SubMgr.MANAGER_PERSON_ID
LEFT JOIN PER_PERSON_NAMES_F_V SubMgr2N
    ON  SubMgr2N.PERSON_ID = SubMgr2.MANAGER_PERSON_ID
    AND SubMgr2N.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN SubMgr2N.EFFECTIVE_START_DATE AND SubMgr2N.EFFECTIVE_END_DATE
LEFT JOIN FirstRequester FR ON FR.PO_HEADER_ID = PHA.PO_HEADER_ID
LEFT JOIN PER_PERSON_NAMES_F_V ReqN
    ON  ReqN.PERSON_ID = FR.REQUESTER_PERSON_ID
    AND ReqN.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN ReqN.EFFECTIVE_START_DATE AND ReqN.EFFECTIVE_END_DATE
LEFT JOIN PersonManager ReqMgr ON ReqMgr.PERSON_ID = FR.REQUESTER_PERSON_ID
LEFT JOIN PER_PERSON_NAMES_F_V ReqMgrN
    ON  ReqMgrN.PERSON_ID = ReqMgr.MANAGER_PERSON_ID
    AND ReqMgrN.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN ReqMgrN.EFFECTIVE_START_DATE AND ReqMgrN.EFFECTIVE_END_DATE
LEFT JOIN PER_PERSON_NAMES_F_V BuyerN
    ON  BuyerN.PERSON_ID = PHA.AGENT_ID
    AND BuyerN.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN BuyerN.EFFECTIVE_START_DATE AND BuyerN.EFFECTIVE_END_DATE
LEFT JOIN PersonManager BuyerMgr ON BuyerMgr.PERSON_ID = PHA.AGENT_ID
LEFT JOIN PER_PERSON_NAMES_F_V BuyerMgrN
    ON  BuyerMgrN.PERSON_ID = BuyerMgr.MANAGER_PERSON_ID
    AND BuyerMgrN.NAME_TYPE = 'GLOBAL'
    AND TRUNC(SYSDATE) BETWEEN BuyerMgrN.EFFECTIVE_START_DATE AND BuyerMgrN.EFFECTIVE_END_DATE
LEFT JOIN GL_CODE_COMBINATIONS GCC ON GCC.CODE_COMBINATION_ID = FR.CCID
LEFT JOIN POLineTotals         PLT ON PLT.PO_HEADER_ID        = PHA.PO_HEADER_ID
WHERE 1 = 1
    AND PHA.SEGMENT1 IS NOT NULL
    AND NVL(PHA.CANCEL_FLAG, 'N') = 'N'
    AND PHA.DOCUMENT_STATUS = 'PENDING APPROVAL'
    AND (:P_PO_NUMBER IS NULL OR :P_PO_NUMBER = '' OR PHA.SEGMENT1  = :P_PO_NUMBER)
    AND (:P_BU_ID     IS NULL OR :P_BU_ID     = '' OR PHA.PRC_BU_ID = TO_NUMBER(:P_BU_ID))
    AND (:P_DAYS_MIN  IS NULL OR :P_DAYS_MIN  = '' OR
         (LSF.ACTION_DATE IS NOT NULL
          AND TRUNC(SYSDATE) - TRUNC(LSF.ACTION_DATE) >= TO_NUMBER(:P_DAYS_MIN)))
ORDER BY
    CASE WHEN LSF.ACTION_DATE IS NOT NULL
         THEN TRUNC(SYSDATE) - TRUNC(LSF.ACTION_DATE)
         ELSE 9999
    END DESC,
    PLT.TOTAL_AMOUNT DESC
