"""
Oracle Fusion Cloud Procurement - Purchasing Tables & Views Schema Reference
Source: https://docs.oracle.com/en/cloud/saas/procurement/26a/oedmp/
"""

# ============================================================================
# TABLE RELATIONSHIPS (JOIN KEYS)
# ============================================================================
RELATIONSHIPS = {
    "PO_HEADERS_ALL -> PO_LINES_ALL": "PO_HEADERS_ALL.PO_HEADER_ID = PO_LINES_ALL.PO_HEADER_ID",
    "PO_LINES_ALL -> PO_LINE_LOCATIONS_ALL": "PO_LINES_ALL.PO_LINE_ID = PO_LINE_LOCATIONS_ALL.PO_LINE_ID",
    "PO_LINE_LOCATIONS_ALL -> PO_DISTRIBUTIONS_ALL": "PO_LINE_LOCATIONS_ALL.LINE_LOCATION_ID = PO_DISTRIBUTIONS_ALL.LINE_LOCATION_ID",
    "PO_HEADERS_ALL -> PO_DISTRIBUTIONS_ALL": "PO_HEADERS_ALL.PO_HEADER_ID = PO_DISTRIBUTIONS_ALL.PO_HEADER_ID",
    "PO_HEADERS_ALL -> PO_LINE_LOCATIONS_ALL": "PO_HEADERS_ALL.PO_HEADER_ID = PO_LINE_LOCATIONS_ALL.PO_HEADER_ID",
    "PO_LINES_ALL -> PO_DISTRIBUTIONS_ALL": "PO_LINES_ALL.PO_LINE_ID = PO_DISTRIBUTIONS_ALL.PO_LINE_ID",
    "PO_HEADERS_ALL -> PO_ACTION_HISTORY": "PO_HEADERS_ALL.PO_HEADER_ID = PO_ACTION_HISTORY.OBJECT_ID",
    "PO_HEADERS_ALL -> PO_VERSIONS": "PO_HEADERS_ALL.PO_HEADER_ID = PO_VERSIONS.PO_HEADER_ID",
    "PO_HEADERS_ALL -> PO_AGENTS": "PO_HEADERS_ALL.AGENT_ID = PO_AGENTS.AGENT_ID",
}

# ============================================================================
# CORE TABLES - Detailed Column Definitions
# ============================================================================

PO_HEADERS_ALL = {
    "description": "Purchase order and agreement headers. Contains one row per PO/BPA/CPA/PA document.",
    "primary_key": "PO_HEADER_ID",
    "columns": {
        "PO_HEADER_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document header unique identifier"},
        "SEGMENT1": {"type": "VARCHAR2(30)", "nullable": True, "desc": "PO Number (document number)"},
        "TYPE_LOOKUP_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Document type: STANDARD, BLANKET, CONTRACT, PLANNED"},
        "DOCUMENT_STATUS": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Header status"},
        "AGENT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Buyer unique identifier (FK to PO_AGENTS)"},
        "VENDOR_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Supplier unique identifier"},
        "VENDOR_SITE_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Supplier site unique identifier"},
        "VENDOR_CONTACT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Supplier contact unique identifier"},
        "CURRENCY_CODE": {"type": "VARCHAR2(15)", "nullable": True, "desc": "Currency code (FK to FND_CURRENCIES)"},
        "RATE_TYPE": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Currency conversion rate type"},
        "RATE_DATE": {"type": "DATE", "nullable": True, "desc": "Currency conversion date"},
        "RATE": {"type": "NUMBER", "nullable": True, "desc": "Currency conversion rate"},
        "SHIP_TO_LOCATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Ship-to location (FK to HR_LOCATIONS_ALL)"},
        "BILL_TO_LOCATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Bill-to location (FK to HR_LOCATIONS_ALL)"},
        "TERMS_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Payment terms (FK to AP_TERMS_TL)"},
        "FOB_LOOKUP_CODE": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Free-on-board terms"},
        "FREIGHT_TERMS_LOOKUP_CODE": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Freight terms"},
        "BLANKET_TOTAL_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Agreed amount for blanket/planned PO"},
        "AMOUNT_LIMIT": {"type": "NUMBER", "nullable": True, "desc": "Max amount that can be released (Blanket/Planned/Contract)"},
        "MIN_RELEASE_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Minimum release amount"},
        "AMOUNT_RELEASED": {"type": "NUMBER", "nullable": True, "desc": "Amount released against agreement"},
        "REVISION_NUM": {"type": "NUMBER", "nullable": True, "desc": "Document revision number"},
        "REVISED_DATE": {"type": "DATE", "nullable": True, "desc": "Date last revised"},
        "APPROVED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - whether PO is approved"},
        "APPROVED_DATE": {"type": "DATE", "nullable": True, "desc": "Date last approved"},
        "CANCEL_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - whether PO is cancelled"},
        "CLOSED_DATE": {"type": "DATE", "nullable": True, "desc": "Date document was closed"},
        "FROZEN_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - whether document is frozen"},
        "CONFIRMING_ORDER_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - confirming order"},
        "ACCEPTANCE_REQUIRED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - supplier acceptance required"},
        "ACCEPTANCE_DUE_DATE": {"type": "DATE", "nullable": True, "desc": "Supplier acceptance due date"},
        "NOTE_TO_VENDOR": {"type": "VARCHAR2(1000)", "nullable": True, "desc": "Note to supplier"},
        "NOTE_TO_RECEIVER": {"type": "VARCHAR2(1000)", "nullable": True, "desc": "Note to receiver"},
        "VENDOR_ORDER_NUM": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Supplier document number"},
        "COMMENTS": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Descriptive comments"},
        "START_DATE": {"type": "DATE", "nullable": True, "desc": "Effective date of document"},
        "END_DATE": {"type": "DATE", "nullable": True, "desc": "Expiration date of document"},
        "PRC_BU_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Procurement Business Unit ID"},
        "REQ_BU_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Requisition Business Unit ID"},
        "BILLTO_BU_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Bill-to Business Unit ID"},
        "SOLDTO_LE_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Sold-to Legal Entity ID"},
        "STYLE_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Purchasing Style of the document"},
        "CHANGE_SUMMARY": {"type": "VARCHAR2(2000)", "nullable": True, "desc": "Description of changes for approval"},
        "SUBMIT_DATE": {"type": "DATE", "nullable": True, "desc": "Date first submitted for approval"},
        "DOCUMENT_CREATION_METHOD": {"type": "VARCHAR2(30)", "nullable": True, "desc": "How document was created (Autocreate, Enter PO, etc.)"},
        "EMAIL_ADDRESS": {"type": "VARCHAR2(2000)", "nullable": True, "desc": "Supplier email for communication"},
        "SUPPLIER_NOTIF_METHOD": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Supplier notification method"},
        "CONTERMS_EXIST_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - contract terms template attached"},
        "ENCUMBRANCE_REQUIRED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - document to be encumbered"},
        "FUNDS_STATUS": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Whether funds have been reserved"},
        "SIGNATURE_REQUIRED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - signatures required"},
        "MODE_OF_TRANSPORT": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Transportation type (truck, air, boat)"},
        "SERVICE_LEVEL": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Transportation priority"},
        "CARRIER_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Carrier Party ID"},
        "DEFAULT_TAXATION_COUNTRY": {"type": "VARCHAR2(2)", "nullable": True, "desc": "Country for tax calculation"},
        "PAY_ON_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Pay upon receipt indicator"},
        "PCARD_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Procurement card ID"},
        "CREATION_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Row creation date"},
        "CREATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who created the row"},
        "LAST_UPDATE_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Last update date"},
        "LAST_UPDATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who last updated"},
        "OBJECT_VERSION_NUMBER": {"type": "NUMBER(9)", "nullable": True, "desc": "Optimistic locking version"},
        # DFF segments
        "ATTRIBUTE_CATEGORY": {"type": "VARCHAR2(30)", "nullable": True, "desc": "DFF structure definition"},
        "ATTRIBUTE1": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 1"},
        "ATTRIBUTE2": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 2"},
        "ATTRIBUTE3": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 3"},
        "ATTRIBUTE4": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 4"},
        "ATTRIBUTE5": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 5"},
        "ATTRIBUTE6": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 6"},
        "ATTRIBUTE7": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 7"},
        "ATTRIBUTE8": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 8"},
        "ATTRIBUTE9": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 9"},
        "ATTRIBUTE10": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 10"},
        "ATTRIBUTE11": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 11"},
        "ATTRIBUTE12": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 12"},
        "ATTRIBUTE13": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 13"},
        "ATTRIBUTE14": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 14"},
        "ATTRIBUTE15": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 15"},
        "ATTRIBUTE16": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 16"},
        "ATTRIBUTE17": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 17"},
        "ATTRIBUTE18": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 18"},
        "ATTRIBUTE19": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 19"},
        "ATTRIBUTE20": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 20"},
    }
}

PO_LINES_ALL = {
    "description": "Purchase order and agreement lines. Contains one row per PO line.",
    "primary_key": "PO_LINE_ID",
    "columns": {
        "PO_LINE_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document line unique identifier"},
        "PO_HEADER_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document header ID (FK to PO_HEADERS_ALL)"},
        "LINE_NUM": {"type": "NUMBER", "nullable": False, "desc": "Line number"},
        "LINE_TYPE_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Line type ID (FK to PO_LINE_TYPES_B)"},
        "LINE_STATUS": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Line status"},
        "ITEM_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Item ID (FK to EGP_SYSTEM_ITEMS_B)"},
        "ITEM_REVISION": {"type": "VARCHAR2(18)", "nullable": True, "desc": "Item revision"},
        "ITEM_DESCRIPTION": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Item description"},
        "CATEGORY_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Item category ID (FK to EGP_CATEGORIES_B)"},
        "UOM_CODE": {"type": "VARCHAR2(3)", "nullable": True, "desc": "Unit of measure code"},
        "QUANTITY": {"type": "NUMBER", "nullable": True, "desc": "Quantity ordered"},
        "UNIT_PRICE": {"type": "NUMBER", "nullable": True, "desc": "Unit price"},
        "AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Budget amount for temp labor lines"},
        "TAX_EXCLUSIVE_PRICE": {"type": "NUMBER", "nullable": True, "desc": "Price exclusive of taxes"},
        "LIST_PRICE_PER_UNIT": {"type": "NUMBER", "nullable": True, "desc": "List price per unit"},
        "LIST_PRICE": {"type": "NUMBER", "nullable": True, "desc": "Original price per unit"},
        "MARKET_PRICE": {"type": "NUMBER", "nullable": True, "desc": "Market price for the item"},
        "BASE_UNIT_PRICE": {"type": "NUMBER", "nullable": True, "desc": "Base unit price"},
        "NOT_TO_EXCEED_PRICE": {"type": "NUMBER", "nullable": True, "desc": "Price limit (blankets/planned)"},
        "QUANTITY_COMMITTED": {"type": "NUMBER", "nullable": True, "desc": "Agreed quantity (blankets)"},
        "COMMITTED_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Agreed amount (blankets)"},
        "AMOUNT_RELEASED": {"type": "NUMBER", "nullable": True, "desc": "Total value ordered from agreement"},
        "ALLOW_PRICE_OVERRIDE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - price can be changed on release"},
        "MIN_RELEASE_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Minimum release amount"},
        "DISCOUNT_TYPE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Discount type (percent or amount)"},
        "DISCOUNT": {"type": "NUMBER", "nullable": True, "desc": "Discount value"},
        "DISCOUNT_REASON": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Reason for discount"},
        "VENDOR_PRODUCT_NUM": {"type": "VARCHAR2(300)", "nullable": True, "desc": "Supplier item number"},
        "NOTE_TO_VENDOR": {"type": "VARCHAR2(1000)", "nullable": True, "desc": "Note to supplier"},
        "TAXABLE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - line is taxable"},
        "TYPE_1099": {"type": "VARCHAR2(10)", "nullable": True, "desc": "1099 type"},
        "CANCEL_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - line cancelled"},
        "CANCEL_DATE": {"type": "DATE", "nullable": True, "desc": "Cancellation date"},
        "CANCEL_REASON": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Cancellation reason"},
        "CLOSED_DATE": {"type": "DATE", "nullable": True, "desc": "Date line closed"},
        "CLOSED_REASON": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Close reason"},
        "CAPITAL_EXPENSE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - capital expense"},
        "NEGOTIATED_BY_PREPARER_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - buyer negotiated price"},
        "CONSIGNMENT_LINE_FLAG": {"type": "VARCHAR2(1)", "nullable": False, "desc": "Y/N - consignment arrangement"},
        "CONTRACT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Contract PA reference (FK to PO_HEADERS_ALL)"},
        "FROM_HEADER_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Source agreement header ID"},
        "FROM_LINE_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Source agreement line ID"},
        "FROM_LINE_LOCATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Source price break ID"},
        "ORDER_TYPE_LOOKUP_CODE": {"type": "VARCHAR2(25)", "nullable": False, "desc": "Value basis of line"},
        "PURCHASE_BASIS": {"type": "VARCHAR2(30)", "nullable": False, "desc": "Purchase basis of line type"},
        "MATCHING_BASIS": {"type": "VARCHAR2(30)", "nullable": False, "desc": "Matching basis of line type"},
        "PRICE_BREAK_LOOKUP_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Pricing scheme (cumulative/non-cumulative)"},
        "PRICE_TYPE_LOOKUP_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Price type"},
        "EXPIRATION_DATE": {"type": "DATE", "nullable": True, "desc": "Catalog line expiration date"},
        "RETROACTIVE_DATE": {"type": "DATE", "nullable": True, "desc": "Retroactive price change timestamp"},
        "MANUFACTURER": {"type": "VARCHAR2(700)", "nullable": True, "desc": "Manufacturer name"},
        "MANUFACTURER_PART_NUM": {"type": "VARCHAR2(700)", "nullable": True, "desc": "Manufacturer part number"},
        "CONTRACTOR_FIRST_NAME": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Contingent worker first name"},
        "CONTRACTOR_LAST_NAME": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Contingent worker last name"},
        "START_DATE": {"type": "DATE", "nullable": True, "desc": "Assignment start date"},
        "LINE_START_DATE": {"type": "DATE", "nullable": True, "desc": "Effective start date of BPA line"},
        "RETAINAGE_RATE": {"type": "NUMBER", "nullable": True, "desc": "Max retainage withholding percentage"},
        "MAX_RETAINAGE_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Max retainage amount"},
        "PROGRESS_PAYMENT_RATE": {"type": "NUMBER", "nullable": True, "desc": "Financing progress payment rate"},
        "RECOUPMENT_RATE": {"type": "NUMBER", "nullable": True, "desc": "Max recoupment percentage"},
        "FUNDS_STATUS": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Whether line amount is reserved"},
        "SECONDARY_QUANTITY": {"type": "NUMBER", "nullable": True, "desc": "Secondary quantity ordered"},
        "SECONDARY_UOM_CODE": {"type": "VARCHAR2(3)", "nullable": True, "desc": "Secondary UOM"},
        "SHIPPING_UOM_CODE": {"type": "VARCHAR2(3)", "nullable": True, "desc": "Shipping UOM"},
        "SHIPPING_UOM_QUANTITY": {"type": "NUMBER", "nullable": True, "desc": "Quantity in shipping UOM"},
        "PRC_BU_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Procurement BU ID"},
        "REQ_BU_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Requisition BU ID"},
        "AUCTION_HEADER_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Sourcing negotiation ID"},
        "AUCTION_DISPLAY_NUMBER": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Sourcing negotiation number"},
        "BID_NUMBER": {"type": "NUMBER", "nullable": True, "desc": "Sourcing bid number"},
        "CREATION_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Row creation date"},
        "CREATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who created"},
        "LAST_UPDATE_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Last update date"},
        "LAST_UPDATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who last updated"},
        "OBJECT_VERSION_NUMBER": {"type": "NUMBER(9)", "nullable": False, "desc": "Optimistic locking version"},
        "ATTRIBUTE_CATEGORY": {"type": "VARCHAR2(30)", "nullable": True, "desc": "DFF structure definition"},
        "ATTRIBUTE1": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 1"},
        "ATTRIBUTE2": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 2"},
        "ATTRIBUTE3": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 3"},
        "ATTRIBUTE4": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 4"},
        "ATTRIBUTE5": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 5"},
        "ATTRIBUTE6": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 6"},
        "ATTRIBUTE7": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 7"},
        "ATTRIBUTE8": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 8"},
        "ATTRIBUTE9": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 9"},
        "ATTRIBUTE10": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 10"},
        "ATTRIBUTE11": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 11"},
        "ATTRIBUTE12": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 12"},
        "ATTRIBUTE13": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 13"},
        "ATTRIBUTE14": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 14"},
        "ATTRIBUTE15": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 15"},
    }
}

PO_LINE_LOCATIONS_ALL = {
    "description": "Purchase order shipment schedules (schedules/price breaks). One row per shipment on a PO line.",
    "primary_key": "LINE_LOCATION_ID",
    "columns": {
        "LINE_LOCATION_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Shipment schedule unique identifier"},
        "PO_HEADER_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document header ID (FK to PO_HEADERS_ALL)"},
        "PO_LINE_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document line ID (FK to PO_LINES_ALL)"},
        "SHIPMENT_NUM": {"type": "NUMBER", "nullable": False, "desc": "Shipment line number"},
        "SHIPMENT_TYPE": {"type": "VARCHAR2(25)", "nullable": False, "desc": "Type of shipment"},
        "SCHEDULE_STATUS": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Shipment status (SPO only)"},
        "QUANTITY": {"type": "NUMBER", "nullable": True, "desc": "Quantity ordered or break quantity"},
        "QUANTITY_RECEIVED": {"type": "NUMBER", "nullable": True, "desc": "Quantity received to date"},
        "QUANTITY_ACCEPTED": {"type": "NUMBER", "nullable": True, "desc": "Quantity accepted after inspection"},
        "QUANTITY_REJECTED": {"type": "NUMBER", "nullable": True, "desc": "Quantity rejected after inspection"},
        "QUANTITY_BILLED": {"type": "NUMBER", "nullable": True, "desc": "Quantity invoiced by AP"},
        "QUANTITY_CANCELLED": {"type": "NUMBER", "nullable": True, "desc": "Quantity cancelled"},
        "QUANTITY_SHIPPED": {"type": "NUMBER", "nullable": True, "desc": "Quantity shipped"},
        "AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Amount for service lines"},
        "AMOUNT_RECEIVED": {"type": "NUMBER", "nullable": True, "desc": "Amount received for service lines"},
        "AMOUNT_BILLED": {"type": "NUMBER", "nullable": True, "desc": "Amount billed for service lines"},
        "AMOUNT_CANCELLED": {"type": "NUMBER", "nullable": True, "desc": "Amount cancelled"},
        "AMOUNT_REJECTED": {"type": "NUMBER", "nullable": True, "desc": "Amount rejected"},
        "AMOUNT_ACCEPTED": {"type": "NUMBER", "nullable": True, "desc": "Amount accepted"},
        "AMOUNT_SHIPPED": {"type": "NUMBER", "nullable": True, "desc": "Amount pending work confirmation"},
        "UOM_CODE": {"type": "VARCHAR2(3)", "nullable": True, "desc": "Unit of measure"},
        "PRICE_OVERRIDE": {"type": "NUMBER", "nullable": True, "desc": "Order shipment price or break price"},
        "TAX_EXCLUSIVE_PRICE": {"type": "NUMBER", "nullable": True, "desc": "Price exclusive of taxes"},
        "SHIP_TO_LOCATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Ship-to location ID"},
        "SHIP_TO_ORGANIZATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Ship-to organization ID"},
        "NEED_BY_DATE": {"type": "DATE", "nullable": True, "desc": "Requested delivery date"},
        "PROMISED_DATE": {"type": "DATE", "nullable": True, "desc": "Promised delivery date"},
        "LAST_ACCEPT_DATE": {"type": "DATE", "nullable": True, "desc": "Latest acceptable receipt date"},
        "REQUESTED_SHIP_DATE": {"type": "DATE", "nullable": True, "desc": "Requested ship date"},
        "PROMISED_SHIP_DATE": {"type": "DATE", "nullable": True, "desc": "Supplier promised ship date"},
        "ANTICIPATED_ARRIVAL_DATE": {"type": "DATE", "nullable": True, "desc": "Projected delivery date"},
        "TERMS_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Payment terms ID"},
        "CARRIER_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Carrier ID"},
        "FOB_LOOKUP_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "FOB terms"},
        "FREIGHT_TERMS_LOOKUP_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Freight terms"},
        "DESTINATION_TYPE_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Final destination of items"},
        "INSPECTION_REQUIRED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - inspection required before payment"},
        "RECEIPT_REQUIRED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - receipt required before payment"},
        "RECEIVING_ROUTING_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Receipt routing ID"},
        "ACCRUE_ON_RECEIPT_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - accrue on receipt"},
        "MATCH_OPTION": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Match invoice to PO or receipt"},
        "QTY_RCV_TOLERANCE": {"type": "NUMBER", "nullable": True, "desc": "Over-receipt tolerance %"},
        "QTY_RCV_EXCEPTION_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Action when tolerance exceeded"},
        "DAYS_EARLY_RECEIPT_ALLOWED": {"type": "NUMBER", "nullable": True, "desc": "Max days items can be received early"},
        "DAYS_LATE_RECEIPT_ALLOWED": {"type": "NUMBER", "nullable": True, "desc": "Max days items can be received late"},
        "INVOICE_CLOSE_TOLERANCE": {"type": "NUMBER", "nullable": True, "desc": "Auto-close for invoicing tolerance %"},
        "RECEIVE_CLOSE_TOLERANCE": {"type": "NUMBER", "nullable": True, "desc": "Auto-close for receiving tolerance %"},
        "CANCEL_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - shipment cancelled"},
        "CANCEL_DATE": {"type": "DATE", "nullable": True, "desc": "Cancellation date"},
        "CANCEL_REASON": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Cancellation reason"},
        "CLOSED_DATE": {"type": "DATE", "nullable": True, "desc": "Date shipment closed"},
        "CLOSED_REASON": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Close reason"},
        "SHIPMENT_CLOSED_DATE": {"type": "DATE", "nullable": True, "desc": "Closed for both receiving and invoice"},
        "CLOSED_FOR_RECEIVING_DATE": {"type": "DATE", "nullable": True, "desc": "Closed for receiving date"},
        "CLOSED_FOR_INVOICE_DATE": {"type": "DATE", "nullable": True, "desc": "Closed for invoice date"},
        "ENCUMBERED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - shipment encumbered"},
        "ENCUMBERED_DATE": {"type": "DATE", "nullable": True, "desc": "Encumbrance date"},
        "TAXABLE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - shipment taxable"},
        "COUNTRY_OF_ORIGIN_CODE": {"type": "VARCHAR2(2)", "nullable": True, "desc": "Country of manufacture"},
        "DROP_SHIP_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - backing sales order line exists"},
        "SALES_ORDER_NUMBER": {"type": "VARCHAR2(50)", "nullable": True, "desc": "Backing sales order number"},
        "SALES_ORDER_LINE_NUMBER": {"type": "VARCHAR2(50)", "nullable": True, "desc": "Backing sales order line number"},
        "CUSTOMER_PO_NUMBER": {"type": "VARCHAR2(50)", "nullable": True, "desc": "Customer PO number"},
        "VMI_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - VMI shipment"},
        "CONSIGNED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - consigned shipment"},
        "FIRM_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - shipment firmed"},
        "VALUE_BASIS": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Value basis of line location"},
        "MATCHING_BASIS": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Matching basis of line location"},
        "PAYMENT_TYPE": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Pay item type"},
        "DESCRIPTION": {"type": "VARCHAR2(240)", "nullable": True, "desc": "Pay item description"},
        "NOTE_TO_RECEIVER": {"type": "VARCHAR2(1000)", "nullable": True, "desc": "Note to receiver"},
        "MODE_OF_TRANSPORT": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Transportation type"},
        "SERVICE_LEVEL": {"type": "VARCHAR2(30)", "nullable": True, "desc": "Transportation priority"},
        "RETAINAGE_RATE": {"type": "NUMBER", "nullable": True, "desc": "Max retainage withholding %"},
        "BACK_TO_BACK_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - back-to-back order"},
        "PRC_BU_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Procurement BU ID"},
        "REQ_BU_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Requisition BU ID"},
        "SECONDARY_QUANTITY": {"type": "NUMBER", "nullable": True, "desc": "Secondary UOM quantity"},
        "SECONDARY_UOM_CODE": {"type": "VARCHAR2(3)", "nullable": True, "desc": "Secondary UOM code"},
        "CREATION_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Row creation date"},
        "CREATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who created"},
        "LAST_UPDATE_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Last update date"},
        "LAST_UPDATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who last updated"},
        "OBJECT_VERSION_NUMBER": {"type": "NUMBER(9)", "nullable": False, "desc": "Optimistic locking version"},
        "ATTRIBUTE_CATEGORY": {"type": "VARCHAR2(30)", "nullable": True, "desc": "DFF structure definition"},
        "ATTRIBUTE1": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 1"},
        "ATTRIBUTE2": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 2"},
        "ATTRIBUTE3": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 3"},
        "ATTRIBUTE4": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 4"},
        "ATTRIBUTE5": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 5"},
        "ATTRIBUTE6": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 6"},
        "ATTRIBUTE7": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 7"},
        "ATTRIBUTE8": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 8"},
        "ATTRIBUTE9": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 9"},
        "ATTRIBUTE10": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 10"},
    }
}

PO_DISTRIBUTIONS_ALL = {
    "description": "Purchase order distributions. Contains accounting and project info for each distribution.",
    "primary_key": "PO_DISTRIBUTION_ID",
    "columns": {
        "PO_DISTRIBUTION_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Distribution unique identifier"},
        "PO_HEADER_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document header ID (FK to PO_HEADERS_ALL)"},
        "PO_LINE_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document line ID (FK to PO_LINES_ALL)"},
        "LINE_LOCATION_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Shipment schedule ID (FK to PO_LINE_LOCATIONS_ALL)"},
        "DISTRIBUTION_NUM": {"type": "NUMBER", "nullable": True, "desc": "Distribution number"},
        "DISTRIBUTION_TYPE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Distribution type"},
        "SET_OF_BOOKS_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Set of Books ID (FK to GL_SETS_OF_BOOKS)"},
        "CODE_COMBINATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "GL charge account ID (FK to GL_CODE_COMBINATIONS)"},
        "BUDGET_ACCOUNT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "GL budget account ID"},
        "ACCRUAL_ACCOUNT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "GL accrual account ID"},
        "VARIANCE_ACCOUNT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "GL variance account ID"},
        "QUANTITY_ORDERED": {"type": "NUMBER", "nullable": True, "desc": "Quantity ordered on distribution"},
        "QUANTITY_DELIVERED": {"type": "NUMBER", "nullable": True, "desc": "Quantity delivered"},
        "QUANTITY_BILLED": {"type": "NUMBER", "nullable": True, "desc": "Quantity invoiced by AP"},
        "QUANTITY_CANCELLED": {"type": "NUMBER", "nullable": True, "desc": "Quantity cancelled"},
        "AMOUNT_ORDERED": {"type": "NUMBER", "nullable": True, "desc": "Amount ordered (service lines)"},
        "AMOUNT_DELIVERED": {"type": "NUMBER", "nullable": True, "desc": "Amount delivered (service lines)"},
        "AMOUNT_BILLED": {"type": "NUMBER", "nullable": True, "desc": "Amount invoiced by AP"},
        "AMOUNT_CANCELLED": {"type": "NUMBER", "nullable": True, "desc": "Amount cancelled (service lines)"},
        "DESTINATION_TYPE_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Final destination of items"},
        "DESTINATION_ORGANIZATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Destination organization ID"},
        "DESTINATION_SUBINVENTORY": {"type": "VARCHAR2(10)", "nullable": True, "desc": "Subinventory for inventory purchases"},
        "DELIVER_TO_LOCATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Delivery location ID"},
        "DELIVER_TO_PERSON_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Requester person ID"},
        "REQ_DISTRIBUTION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Requisition distribution ID"},
        "RATE_DATE": {"type": "DATE", "nullable": True, "desc": "Currency conversion date"},
        "RATE": {"type": "NUMBER", "nullable": True, "desc": "Currency conversion rate"},
        "ENCUMBERED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - distribution encumbered"},
        "ENCUMBERED_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Encumbered amount"},
        "UNENCUMBERED_QUANTITY": {"type": "NUMBER", "nullable": True, "desc": "Unencumbered quantity"},
        "UNENCUMBERED_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Unencumbered amount"},
        "GL_ENCUMBERED_DATE": {"type": "DATE", "nullable": True, "desc": "Date distribution encumbered"},
        "GL_ENCUMBERED_PERIOD_NAME": {"type": "VARCHAR2(15)", "nullable": True, "desc": "Period encumbered"},
        "GL_CANCELLED_DATE": {"type": "DATE", "nullable": True, "desc": "Date distribution cancelled in GL"},
        "GL_CLOSED_DATE": {"type": "DATE", "nullable": True, "desc": "Date distribution final-closed"},
        "FUNDS_STATUS": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Whether distribution amount reserved"},
        "BUDGET_DATE": {"type": "DATE", "nullable": True, "desc": "Budget date for commitment control"},
        "PREVENT_ENCUMBRANCE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - should distribution be encumbered"},
        "ACCRUE_ON_RECEIPT_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - accrue on receipt"},
        "ACCRUED_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - distribution accrued"},
        "TAX_RECOVERY_OVERRIDE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - tax recovery override"},
        "RECOVERABLE_TAX": {"type": "NUMBER", "nullable": True, "desc": "Recoverable tax amount"},
        "NONRECOVERABLE_TAX": {"type": "NUMBER", "nullable": True, "desc": "Non-recoverable tax amount"},
        "TAX_EXCLUSIVE_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Amount exclusive of taxes"},
        "RECOVERY_RATE": {"type": "NUMBER", "nullable": True, "desc": "Tax recovery percentage"},
        "PJC_PROJECT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Project ID"},
        "PJC_TASK_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Project task ID"},
        "PJC_EXPENDITURE_ITEM_DATE": {"type": "DATE", "nullable": True, "desc": "Project expenditure item date"},
        "PJC_ORGANIZATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Project organization ID"},
        "PJC_EXPENDITURE_TYPE_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Expenditure type ID"},
        "PJC_BILLABLE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - project billable"},
        "PJC_CAPITALIZABLE_FLAG": {"type": "VARCHAR2(1)", "nullable": True, "desc": "Y/N - capitalizable"},
        "PJC_CONTRACT_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Project contract ID"},
        "PJC_WORK_TYPE_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Project work type ID"},
        "PJC_FUNDING_ALLOCATION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Project funding override"},
        "WIP_ENTITY_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "WIP job or assembly ID"},
        "WIP_OPERATION_SEQ_NUM": {"type": "NUMBER", "nullable": True, "desc": "WIP operation sequence"},
        "WIP_RESOURCE_SEQ_NUM": {"type": "NUMBER", "nullable": True, "desc": "WIP resource sequence"},
        "BOM_RESOURCE_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "BOM resource ID"},
        "AMOUNT_FINANCED": {"type": "NUMBER", "nullable": True, "desc": "Pre-paid amount (advances/financing)"},
        "AMOUNT_RECOUPED": {"type": "NUMBER", "nullable": True, "desc": "Liquidated prepayment amount"},
        "RETAINAGE_WITHHELD_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Retainage withheld"},
        "RETAINAGE_RELEASED_AMOUNT": {"type": "NUMBER", "nullable": True, "desc": "Retainage released"},
        "PRC_BU_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Procurement BU ID"},
        "REQ_BU_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Requisition BU ID"},
        "CREATION_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Row creation date"},
        "CREATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who created"},
        "LAST_UPDATE_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Last update date"},
        "LAST_UPDATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who last updated"},
        "OBJECT_VERSION_NUMBER": {"type": "NUMBER(9)", "nullable": True, "desc": "Optimistic locking version"},
        "ATTRIBUTE_CATEGORY": {"type": "VARCHAR2(30)", "nullable": True, "desc": "DFF structure definition"},
        "ATTRIBUTE1": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 1"},
        "ATTRIBUTE2": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 2"},
        "ATTRIBUTE3": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 3"},
        "ATTRIBUTE4": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 4"},
        "ATTRIBUTE5": {"type": "VARCHAR2(150)", "nullable": True, "desc": "DFF segment 5"},
    }
}

PO_ACTION_HISTORY = {
    "description": "Approval and control action history for purchasing documents (POs, requisitions, releases).",
    "primary_key": "OBJECT_ID + SEQUENCE_NUM",
    "columns": {
        "OBJECT_ID": {"type": "NUMBER(18)", "nullable": False, "desc": "Document header unique identifier"},
        "OBJECT_TYPE_CODE": {"type": "VARCHAR2(25)", "nullable": False, "desc": "Document type"},
        "OBJECT_SUB_TYPE_CODE": {"type": "VARCHAR2(25)", "nullable": False, "desc": "Document subtype"},
        "SEQUENCE_NUM": {"type": "NUMBER", "nullable": False, "desc": "Action sequence number"},
        "ACTION_CODE": {"type": "VARCHAR2(25)", "nullable": False, "desc": "Action type (APPROVE, REJECT, SUBMIT, etc.)"},
        "ACTION_DATE": {"type": "DATE", "nullable": True, "desc": "Action date"},
        "PERFORMER_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Person who took action (PARTY_ID or PERSON_ID)"},
        "ROLE_CODE": {"type": "VARCHAR2(30)", "nullable": False, "desc": "Role: BUYER, REQUESTER, APPROVER, CAT_ADMIN, SUPPLIER"},
        "NOTE": {"type": "VARCHAR2(4000)", "nullable": True, "desc": "Note or reason for action"},
        "OBJECT_REVISION_NUM": {"type": "NUMBER", "nullable": True, "desc": "Document revision number"},
        "PO_VERSION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "PO version ID"},
        "PARENT_VERSION_ID": {"type": "NUMBER(18)", "nullable": True, "desc": "Parent PO/CO version ID"},
        "ASSIGNMENT_DATE": {"type": "DATE", "nullable": True, "desc": "Date assigned to user for action"},
        "OFFLINE_CODE": {"type": "VARCHAR2(25)", "nullable": True, "desc": "Whether sent to offline approver"},
        "SUPPLIER_ACCESSIBLE_FLAG": {"type": "VARCHAR2(1)", "nullable": False, "desc": "Y/N - accessible to supplier"},
        "ERROR_CODE": {"type": "VARCHAR2(128)", "nullable": True, "desc": "Error code for action"},
        "CREATION_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Row creation date"},
        "CREATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who created"},
        "LAST_UPDATE_DATE": {"type": "TIMESTAMP", "nullable": False, "desc": "Last update date"},
        "LAST_UPDATED_BY": {"type": "VARCHAR2(64)", "nullable": False, "desc": "User who last updated"},
        "OBJECT_VERSION_NUMBER": {"type": "NUMBER(9)", "nullable": False, "desc": "Optimistic locking version"},
    }
}

# ============================================================================
# SUPPORTING TABLES (summary definitions)
# ============================================================================

SUPPORTING_TABLES = {
    "PO_AGENTS": "Purchasing agents/buyers. Key cols: AGENT_ID, AGENT_NAME",
    "PO_AGENT_ACCESSES": "Agent access permissions by document type and BU",
    "PO_APPROVED_SUPPLIER_LIST": "Approved supplier list (ASL) entries",
    "PO_ASL_ATTRIBUTES": "Attributes for ASL entries (lead time, min order, etc.)",
    "PO_ASL_DOCUMENTS": "Documents linked to ASL entries",
    "PO_ASL_STATUSES": "ASL status tracking",
    "PO_DOCUMENT_TYPES_ALL_B": "Document type definitions (base). Key cols: DOCUMENT_TYPE_CODE, DOCUMENT_SUBTYPE",
    "PO_DOCUMENT_TYPES_ALL_TL": "Document type translations",
    "PO_DOC_STYLE_HEADERS": "Document style headers",
    "PO_LINE_TYPES_B": "Line type definitions. Key cols: LINE_TYPE_ID, ORDER_TYPE_LOOKUP_CODE",
    "PO_LINE_TYPES_TL": "Line type translations",
    "PO_SYSTEM_PARAMETERS_ALL": "System-level purchasing parameters per BU",
    "PO_VERSIONS": "PO version tracking. Key cols: PO_VERSION_ID, PO_HEADER_ID, VERSION_NUM",
    "PO_HAZARD_CLASSES_B": "Hazard class definitions",
    "PO_UN_NUMBERS_B": "UN hazardous material numbers",
    "PO_NOTIFICATION_CONTROLS": "Notification control settings",
    "PO_BUYER_ASSIGNMENT_RULES": "Buyer auto-assignment rules",
    "PO_GA_ORG_ASSIGNMENTS": "Global agreement organization assignments",
    "PO_INTERFACE_ERRORS": "Import/interface processing errors",
    "PO_HEADERS_INTERFACE": "Import interface for PO headers",
    "PO_LINES_INTERFACE": "Import interface for PO lines",
    "PO_LINE_LOCATIONS_INTERFACE": "Import interface for shipment schedules",
    "PO_DISTRIBUTIONS_INTERFACE": "Import interface for distributions (not in 26A)",
    "PO_ATTRIBUTE_VALUES": "Catalog attribute values for negotiation items",
    "PO_ATTRIBUTE_VALUES_TLP": "Translatable catalog attribute values",
    "PO_HEADERS_ARCHIVE_ALL": "Archived PO headers (revision history)",
    "PO_LINES_ARCHIVE_ALL": "Archived PO lines (revision history)",
    "PO_LINE_LOCATIONS_ARCHIVE_ALL": "Archived shipment schedules (revision history)",
    "PO_DISTRIBUTIONS_ARCHIVE_ALL": "Archived distributions (revision history)",
    "PO_HEADERS_DRAFT_ALL": "Draft/pending change PO headers",
    "PO_LINES_DRAFT_ALL": "Draft/pending change PO lines",
    "PO_LINE_LOCATIONS_DRAFT_ALL": "Draft/pending change shipment schedules",
    "PO_DISTRIBUTIONS_DRAFT_ALL": "Draft/pending change distributions",
}

# ============================================================================
# COMMON VIEWS
# ============================================================================

VIEWS = {
    "PO_AGENTS_V": "Purchasing agents view with person details",
    "PO_BUYERS_VAL_V": "Buyer validation view",
    "PO_SUPPLIERS_VAL_V": "Supplier validation view",
    "PO_SUPPLIER_SITES_VAL_V": "Supplier sites validation view",
    "PO_SUPPLIER_CONTACTS_VAL_V": "Supplier contacts validation view",
    "PO_SUPPLIER_PO_SITES_VAL_V": "Supplier PO sites validation view",
    "PO_APPROVED_SUPPLIER_LIS_VAL_V": "ASL validation view",
    "PO_ASL_ATTRIBUTES_VAL_V": "ASL attributes validation view",
    "PO_COMMODITY_V": "Commodity master view",
    "PO_LINE_TYPES_V": "Line types view",
    "PO_LINE_TYPES_VL": "Line types translated view",
    "PO_DOCUMENT_TYPES_VL": "Document types translated view",
    "PO_LOCATIONS_VAL_V": "Locations validation view",
    "PO_UNITS_OF_MEASURE_VAL_V": "UOM validation view",
    "PO_LOOKUP_CODES": "Lookup codes for PO module",
    "PO_HAZARD_CLASSES_VL": "Hazard classes translated view",
    "PO_UN_NUMBERS_VL": "UN numbers translated view",
    "PO_DISTRIBUTIONS_AP_V": "Distributions view for Accounts Payable",
    "PO_DOC_STYLE_LINES_VL": "Document style lines translated view",
    "PO_CO_TEMPLATES_VL": "Catalog templates translated view",
    "PO_INTG_LINES_V": "Integration view for PO lines",
    "PO_INTG_LINE_LOCATIONS_V": "Integration view for line locations",
    "PO_INTG_DISTRIBUTIONS_V": "Integration view for distributions",
    "PO_SCO_INTEGRATION_V": "Supply Chain Orchestration integration view",
    "PO_PJC_COMMITMENTS_V": "Project Costing commitments view",
    "PO_XLA_DETAILS_V": "Subledger Accounting details view",
    "PO_XLA_HEADERS_V": "Subledger Accounting headers view",
    "PO_XLA_TRANSACTIONS_V": "Subledger Accounting transactions view",
    "PO_VERSIONS_UNPROCESSED_V": "Unprocessed PO versions view",
}

# ============================================================================
# LOOKUP VALUES (common lookup types)
# ============================================================================

LOOKUP_VALUES = {
    "TYPE_LOOKUP_CODE (PO_HEADERS_ALL)": [
        "STANDARD - Standard Purchase Order",
        "BLANKET - Blanket Purchase Agreement",
        "CONTRACT - Contract Purchase Agreement",
        "PLANNED - Planned Purchase Order",
    ],
    "DOCUMENT_STATUS (PO_HEADERS_ALL)": [
        "INCOMPLETE",
        "REQUIRES REAPPROVAL",
        "IN PROCESS",
        "PRE-APPROVED",
        "APPROVED",
        "NOT SUBMITTED",
        "REJECTED",
        "WITHDRAWN",
        "SENT",
        "ACCEPTED",
        "CLOSED",
        "CANCELLED",
        "ON HOLD",
        "PENDING CANCEL",
        "FINALLY CLOSED",
    ],
    "ACTION_CODE (PO_ACTION_HISTORY)": [
        "SUBMIT - Document submitted",
        "APPROVE - Document approved",
        "REJECT - Document rejected",
        "FORWARD - Forwarded to another approver",
        "RETURN - Returned to preparer",
        "WITHDRAW - Withdrawn from approval",
        "CLOSE - Document closed",
        "CANCEL - Document cancelled",
        "FREEZE - Document frozen",
        "HOLD - Document placed on hold",
        "RELEASE HOLD - Hold released",
        "FINALLY CLOSE - Finally closed",
        "OPEN - Document re-opened",
    ],
    "DESTINATION_TYPE_CODE": [
        "INVENTORY - Inventory destination",
        "EXPENSE - Expense destination",
        "SHOP FLOOR - WIP/Manufacturing",
    ],
    "ORDER_TYPE_LOOKUP_CODE (PO_LINES_ALL)": [
        "QUANTITY - Quantity-based line",
        "AMOUNT - Amount-based line",
        "FIXED PRICE - Fixed price line",
        "RATE - Rate-based line",
    ],
    "SHIPMENT_TYPE (PO_LINE_LOCATIONS_ALL)": [
        "STANDARD - Standard PO shipment",
        "PLANNED - Planned PO shipment",
        "BLANKET - Blanket release shipment",
        "SCHEDULED - Scheduled release shipment",
        "PRICE BREAK - Blanket price break",
        "QUOTATION - Quotation shipment",
        "RFQ - RFQ shipment",
    ],
}

# ============================================================================
# ALL TABLE DEFINITIONS (for lookup)
# ============================================================================

ALL_TABLES = {
    "PO_HEADERS_ALL": PO_HEADERS_ALL,
    "PO_LINES_ALL": PO_LINES_ALL,
    "PO_LINE_LOCATIONS_ALL": PO_LINE_LOCATIONS_ALL,
    "PO_DISTRIBUTIONS_ALL": PO_DISTRIBUTIONS_ALL,
    "PO_ACTION_HISTORY": PO_ACTION_HISTORY,
}
